config/routes.rb
Wavelength::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "static_pages#home"
  get "dashboard" => "static_pages#dashboard"

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-out", to: "devise/sessions#destroy"
    get "sign-up", to: "devise/registrations#new"
    post "users/toggle-admin", to: "registrations#toggle_admin"
    post "users/invite-user", to: "registrations#invite_user"
  end

  namespace "chat" do
    root to: "static_pages#index"
    post "upload", to: "static_pages#upload"
    post "remove_file", to: "static_pages#remove_file"
  end

  namespace "pm" do
    root to: "static_pages#dashboard"
    get "dashboard", to: "static_pages#dashboard"
  end

  namespace "wiki" do
    root to: "static_pages#dashboard"
    get "dashboard", to: "static_pages#dashboard"

    resources :spaces do
      get "archive", to: "spaces#archive"

      resources :pages do 
        get "archive", to: "pages#archive"

        resources :page_comments
      end
    end
  end
end

app/models/page_comment.rb
class PageComment < ActiveRecord::Base
  has_ancestry

  belongs_to :page
  belongs_to :user

  validates_presence_of :content
end

app/controllers/wiki/page_comments_controller.rb
class Wiki::PageCommentsController < WikiController
  before_action :authenticate_user!

  def create
    @page_comment = PageComment.new(page_comment_params)
    @page_comment.page_id = params[:page_id]
    @page_comment.user_id = current_user.id
    if @page_comment.save!
      flash[:success] = "Thank you for commenting on this page!"
      redirect_to :back
    else
      flash[:error] = "Something went wrong! Please try again."
      redirect_to :back
    end
  end

  def update
    @page_comment = PageComment.find(params[:id])
    if @page_comment.update!(page_comment_params)
      flash[:success] = "Your comment has been updated!"
      redirect_to :back
    else
      flash[:error] = "Something went wrong! Please try again."
      redirect_to :back
    end
  end

  def destroy
    @page_comment = PageComment.find(params[:id])
    @page_comment.destroy
    flash[:warning] = "Your comment and all replies (if any) hav been deleted."
    redirect_to :back
  end

  private
    def page_comment_params
      params.require(:page_comment).permit(:page_id, :user_id, :parent_id, :content, :_destroy)
    end
end

app/controllers/wiki/pages_controller.rb
class Wiki::PagesController < WikiController
  before_action :authenticate_user!

  def show
    @space = Space.find(params[:space_id])
    @page = Page.find(params[:id])
    @page_comment = PageComment.new

    add_breadcrumb @space.name, wiki_space_path(@space)
    @page.ancestors.each do |a|
      add_breadcrumb a.name, wiki_space_page_path(@space, a)
    end
    add_breadcrumb @page.name, wiki_space_page_path(@space, @page)
  end

  def new
    @space = Space.find(params[:space_id])
    @pages_for_select = ancestry_options(Page.arrange(space_id: params[:space_id], order: "sort_order ASC, name ASC")) { |i| "#{"-" * i.depth} #{i.name}" }
    @page = Page.new
  end

  def create
    @space = Space.find(params[:space_id])
    @page = Page.new(page_params)
    if @page.save
      flash[:success] = "#{@page.name} has been created!"
      redirect_to wiki_space_page_path(params[:space_id], @page.id)
    else
      @pages_for_select = ancestry_options(Page.arrange(space_id: params[:space_id], order: "sort_order ASC, name ASC")) { |i| "#{"-" * i.depth} #{i.name}" }
      flash.now[:error] = "Something went wrong! Please try again."
      render :new
    end
  end

  def edit
    @space = Space.find(params[:space_id])
    @pages_for_select = ancestry_options(Page.arrange(space_id: params[:space_id], order: "sort_order ASC, name ASC")) { |i| "#{"-" * i.depth} #{i.name}" }
    @page = Page.find(params[:id])

    add_breadcrumb @space.name, wiki_space_path(@space)
    @page.ancestors.each do |a|
      add_breadcrumb a.name, wiki_space_page_path(@space, a)
    end
    add_breadcrumb @page.name, wiki_space_page_path(@space, @page)
    add_breadcrumb "Edit Page", edit_wiki_space_page_path(@space, @page)
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      flash[:notice] = "#{@page.name} has been updated!"
      redirect_to wiki_space_page_path(params[:space_id], params[:id])
    else
      @space = Space.find(params[:space_id])
      @pages_for_select = ancestry_options(Page.arrange(space_id: params[:space_id], order: "sort_order ASC, name ASC")) { |i| "#{"-" * i.depth} #{i.name}" }
      flash.now[:error] = "Something went wrong! Please try again."
      render :edit
    end
  end

  def destroy
    @space = Space.find(params[:space_id])
    @page = Page.find(params[:id])
    @page.destroy
    flash[:warning] = "#{@page.name} has been deleted."
    redirect_to wiki_space_path(@space)
  end

  def archive
    @page = Page.find(params[:page_id])
    @page.status = false
    if @page.save
      flash[:success] = "#{@page.name} has been archived!"
      redirect_to wiki_space_path(params[:space_id])
    else
      flash[:error] = "Something went wrong! Please try again."
      redirect_to :back
    end
  end

  def add_page_comment
    @space = Space.find(params[:space_id])
    @page = Page.find(params[:page_id])
    @page_comment = PageComment.new(page_params)
    if @page_comment.save
      flash[:success] = "Thank you for commenting on this page!"
      redirect_to :back
    else
      @pages_for_select = ancestry_options(Page.arrange(space_id: params[:space_id], order: "sort_order ASC, name ASC")) { |i| "#{"-" * i.depth} #{i.name}" }

      add_breadcrumb @space.name, wiki_space_path(@space)
      @page.ancestors.each do |a|
        add_breadcrumb a.name, wiki_space_page_path(@space, a)
      end
      add_breadcrumb @page.name, wiki_space_page_path(@space, @page)

      flash.now[:error] = "Something went wrong! Please try again."
      render :new
    end
  end

  private
    def page_params
      params.require(:page).permit(:space_id, :user_id, :parent_id, :name, :description, :content, :sort_oder, :status, :_destroy, {user_attributes: [:id, :organization_id, :email, :display_name, :is_admin]}, {page_attachments_attributes: [:id, :page_id, :name, :file, :aws_path, :remove_file, :_destroy]}, {page_comments_attributes: [:id, :page_id, :user_id, :parent_id, :content, :_destroy]})
    end

    def ancestry_options(items, &block)
      return ancestry_options(items){ |i| "#{"-" * i.depth} #{i.name}" } unless block_given?

      result = []
      items.map do |item, sub_items|
        result << [yield(item), item.id]
        result += ancestry_options(sub_items, &block)
      end
      result
    end
end

app/controllers/wiki/spaces_controller.rb
class Wiki::SpacesController < WikiController
  before_action :authenticate_user!

  def show
    @space = Space.find(params[:id])
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.organization_id = current_user.organization_id
    if @space.save
      flash[:success] = "#{@space.name} has been created!"
      redirect_to wiki_space_path(@space)
    else
      flash.now[:error] = "Something went wrong! Please try again."
      render :new
    end
  end

  def edit
    @space = Space.find(params[:id])
  end

  def update
    @space = Space.find(params[:id])
    if @space.update(space_params)
      flash[:notice] = "#{@space.name} has been updated!"
      redirect_to wiki_space_path(@space)
    else
      flash.now[:error] = "Something went wrong! Please try again."
      render :edit
    end
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy
    flash[:warning] = "#{@space.name} has been deleted."
    redirect_to wiki_root_path
  end

  def archive
    @space = Space.find(params[:space_id])
    @space.status = false
    if @space.save
      flash[:success] = "#{@space.name} has been archived!"
      redirect_to wiki_root_path
    else
      flash[:error] = "Something went wrong! Please try again."
      redirect_to :back
    end
  end

  private
    def space_params
      params.require(:space).permit(:organization_id, :name, :description, :status, :_destroy, {pages_attributes: [:id, :user_id, :space_id, :parent_id, :name, :description, :content, :sort_oder, :status, :_destroy]})
    end
end

app/controllers/wiki/static_pages_controller.rb
class Wiki::StaticPagesController < WikiController
  before_action :authenticate_user!

  def dashboard
    @spaces = Space.paginate(page: params[:page], per_page: 20).where("organization_id = ? AND status = ?", current_user.organization.id, true).order("id DESC")

    @pages = []
    Space.where("organization_id = ?", current_user.organization.id).each do |s|
      s.pages.each { |p| @pages << p }
    end
    @pages.sort_by { |p| p[:updated_at] }.reverse
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  before_action :authenticate_user!

  layout "wiki_application"
end

app/helpers/wiki_helper.rb
module WikiHelper
  # Returns the full title on a per-page basis.
  def wiki_full_title(page_title)
    base_title = "Wiki | Wavelength"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}".html_safe
    end
  end

  def display_pages_in_space
    space = params[:space_id] ? params[:space_id] : params[:id]
    if space
      @root_pages_for_current_space = @space.pages.where(ancestry: nil).order("sort_order ASC, id ASC")
      @pages_for_current_space = []
      @root_pages_for_current_space.each do |rp|
        @pages_for_current_space << rp.subtree.arrange(order: "sort_order ASC, name ASC")
      end
      build_pages_navigation @pages_for_current_space
    end
  end

  def build_pages_navigation(root_pages)
    root_pages.map do |pages|
      nested_pages pages
    end.join.html_safe
  end

  def nested_pages(pages)
    pages.map do |page, sub_pages|
      render(page) + (content_tag(:ul, nested_pages(sub_pages), class: "nested-pages list-unstyled") unless sub_pages.blank?)
    end.join.html_safe
  end

  def display_page_comments
    page = params[:id]
    if page
      @root_comments_for_current_page = @page.page_comments.where(ancestry: nil).order("id DESC")
      @comments_for_current_page = []
      @root_comments_for_current_page.each do |rc|
        @comments_for_current_page << rc.subtree.arrange(order: "id DESC")
      end
      build_comment_structure @comments_for_current_page
    end
  end

  def build_comment_structure(root_comments)
    root_comments.map do |comments|
      nested_comments comments
    end.join.html_safe
  end

  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + (content_tag(:ul, nested_comments(sub_comments), class: "nested-comments list-unstyled") unless sub_comments.blank?)
    end.join.html_safe
  end
end

app/views/wiki/page_comments/_page_comment.html.erb
<li class="comment panel">
  <div class="row">
    <div class="comment-author col-md-6">
      <%= page_comment.user.display_name.upcase %> said...
    </div>
    <div class="col-md-6 text-right">
      <div class="comment-timestamp">
        on <%= page_comment.created_at.strftime("%b, %e at %I:%M %P").upcase %>
      </div>
      <% if page_comment.user == current_user %>
        <div class="comment-actions">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <%= link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, wiki_space_page_page_comment_path(@space, @page, page_comment), { method: :delete, "data-confirm" => "Are you sure you want to delete your comment?" } %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="comment-content col-md-12">
      <%= markdown(page_comment.content) %>
      <%= "<div class='comment-last-updated'>Last Updated #{page_comment.updated_at.strftime("%b, %e at %I:%M %P")}</div>".html_safe if page_comment.created_at != page_comment.updated_at %>
    </div>
    <div class="comment-edit-form col-md-12">
      <%= form_for page_comment, url: wiki_space_page_page_comment_path(@space, @page, page_comment), html: { role: "form", class: "update-comment-form" } do |f| %>
          <%= render "shared/error_messages", obj: page_comment %>
          <fieldset>
            <div class="form-group">
              <%= f.label :content, "Update Comment" %>
              <%= f.text_area :content, class: "form-control", rows: 4 %>
            </div>
          </fieldset>
          <div class="form-actions">
            <%= f.submit "Update", class: "button button-primary" %>
          </div>
        <% end %>
    </div>
  </div>
</li>
<div class="comment-reply">
  <a href="#" class="comment-reply-link">Reply to Comment<%= " (#{page_comment.children.count})" if page_comment.children.count > 0 %></a>
  <div class="comment-form">
    <div class="row">
      <div class="col-md-6">
        <%= form_for @page_comment, url: wiki_space_page_page_comments_path(@space, @page), html: { role: "form", class: "reply-comment-form" } do |f| %>
          <%= render "shared/error_messages", obj: @page_comment %>
          <fieldset>
            <div class="form-group">
              <%= f.label :content, "Reply to Comment" %>
              <%= f.text_area :content, class: "form-control", rows: 4 %>
              <%= f.hidden_field :parent_id, value: page_comment.id %>
            </div>
          </fieldset>
          <div class="form-actions">
            <%= f.submit "Reply", class: "button button-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>