config/routes.rb
Wavelength::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "static_pages#home"
  get "dashboard" => "static_pages#dashboard"

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-out", to: "devise/sessions#destroy"
    get "sign-up", to: "devise/registrations#new"
    post "users/toggle-admin", to: "registrations#toggle_admin"
    post "users/invite-user", to: "registrations#invite_user"
  end

  namespace "chat" do
    root to: "static_pages#index"
    post "upload", to: "static_pages#upload"
    post "remove_file", to: "static_pages#remove_file"
  end

  namespace "pm" do
    root to: "static_pages#dashboard"
    get "dashboard", to: "static_pages#dashboard"
  end

  namespace "wiki" do
    root to: "static_pages#dashboard"
    get "dashboard", to: "static_pages#dashboard"

    resources :spaces do
      get "archive", to: "spaces#archive"

      resources :pages do 
        get "archive", to: "pages#archive"

        resources :page_comments
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable

  belongs_to :organization
  has_many :pages
  has_many :page_comments, dependent: :destroy

  accepts_nested_attributes_for :organization

  validates_presence_of :display_name
end

app/views/users/shared/_links.erb
<aside class="form-help-links">
  <% if controller_name != "sessions" %>
    Already have an account? <%= link_to "Sign In", sign_in_path %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != "registrations" %>
    Don't have an account? <%= link_to "Sign Up", sign_up_path %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
    Forgot your password? <%= link_to "Reset It", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != "confirmations" %>
    Didn't receive confirmation instructions? <%= link_to "Resend Instructions", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks" %>
    Didn't receive unlock instructions? <%= link_to "Resend Instructions", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      Sign in with <%= link_to provider.to_s.titleize, omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</aside>