config/routes.rb
Wavelength::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "static_pages#home"
  get "dashboard" => "static_pages#dashboard"

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
    get "sign-out", to: "devise/sessions#destroy"
    get "sign-up", to: "devise/registrations#new"
    post "users/toggle-admin", to: "registrations#toggle_admin"
    post "users/invite-user", to: "registrations#invite_user"
  end

  namespace "chat" do
    root to: "static_pages#index"
    post "upload", to: "static_pages#upload"
    post "remove_file", to: "static_pages#remove_file"
  end

  namespace "pm" do
    root to: "static_pages#dashboard"
    get "dashboard", to: "static_pages#dashboard"
  end

  namespace "wiki" do
    root to: "static_pages#dashboard"
    get "dashboard", to: "static_pages#dashboard"

    resources :spaces do
      get "archive", to: "spaces#archive"

      resources :pages do 
        get "archive", to: "pages#archive"

        resources :page_comments
      end
    end
  end
end

app/views/shared/_app_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      &copy; <%= Time.now.year %> Wavelength
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign In", sign_in_path %></li>
        <li><%= link_to "Sign Up", sign_up_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/shared/_app_header.html.erb
<header class="app-nav navbar navbar-inverse" role="navigation">
  <nav class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#app-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </nav>
  <nav class="collapse navbar-collapse" id="app-navbar-collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Chat", chat_root_path, class: controller_path.start_with?("chat") ? "active": ""; %></li>
      <li><%= link_to "Project Management", pm_root_path, class: controller_path.start_with?("pm") ? "active": ""; %></li>
      <li><%= link_to "Wiki", wiki_root_path, class: controller_path.start_with?("wiki") ? "active": ""; %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Dashboard", dashboard_path, class: current_page?(dashboard_path) ? "active" : ""; %></li>
      <li><%= link_to "My Account", edit_user_registration_path, class: current_page?(edit_user_registration_path) ? "active" : ""; %></li>
      <li><%= link_to "Sign Out", sign_out_path %></li>
    </ul>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <section id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> found with this form:</h2>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <article class="<%= flash_class(key) %> alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value %>
  </article>
<% end %>

app/views/shared/_site_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      &copy; <%= Time.now.year %> Wavelength
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign In", sign_in_path %></li>
        <li><%= link_to "Sign Up", sign_up_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/shared/_site_header.html.erb
<header class="site-nav navbar navbar-default" role="navigation">
  <div class="container">
    <nav class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wavelength", root_path, class: "navbar-brand" %>
    </nav>
    <nav class="collapse navbar-collapse" id="site-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign Up", sign_up_path %></li>
        <li><%= link_to "Sign In", sign_in_path, class: "button button-m button-primary" %></li>
      </ul>
    </nav>
  </div>
</header>